### ISSUE TITLE
Adapter module details

### ISSUE THREAD

**Issue by akshitac8** [Paranioar/UniPT#1]
Hi @Paranioar thank you sharing your work. Can you please share details about the adapter module, was only able to find this https://github.com/Paranioar/UniPT/blob/main/CLIP4Clip/modules/module_adapter.py but not able to see where its called.

Thank you for your help.

**Comment by Paranioar** [comment]
> akshitac8

Thanks for your attention to our UniPT. Due to overloaded issues, I am sorry that I only wrote a concise README.md without too many details. I summarize the positions where UniPT is defined and invoked in each work as follows:

In CLIP-ViL, 
UniPT is defined and called at **class LXRTEncoder(nn.Module)** from [CLIP-ViL/src/lxrt/modeling.py](https://github.com/Paranioar/UniPT/blob/main/CLIP-ViL/src/lxrt/modeling.py).

In CLIP4Clip,
UniPT is defined at [CLIP4Clip/modules/module_adapter.py](https://github.com/Paranioar/UniPT/blob/main/CLIP4Clip/modules/module_adapter.py), and called at **Line 251-261** from [CLIP4Clip/modules/modeling.py](https://github.com/Paranioar/UniPT/blob/main/CLIP4Clip/modules/modeling.py).

In GPO,
UniPT is defined at [GPO/lib/adapter_for_cnn.py](https://github.com/Paranioar/UniPT/blob/main/GPO/lib/adapter_for_cnn.py) and [GPO/lib/adapter_for_transformer.py](https://github.com/Paranioar/UniPT/blob/main/GPO/lib/adapter_for_transformer.py), and called at [GPO/lib/encoders.py](https://github.com/Paranioar/UniPT/blob/main/GPO/lib/encoders.py).

In MDETR,
UniPT is defined and called at **class Transformer(nn.Module)** from [MDETR/models/transformer.py](https://github.com/Paranioar/UniPT/blob/main/MDETR/models/transformer.py).

I hope these help you quickly realize your idea beyond UniPT. Please don't hesitate to let me know if you have any more questions.

**Comment by akshitac8** [comment]
thank you for reply. Can you please share the training commands as well.

**Comment by Paranioar** [comment]
> thank you for reply. Can you please share the training commands as well.

All the training.sh files have been shared as follows:

CLIP-ViL/scripts/side_transformers_gqa.sh
CLIP-ViL/scripts/side_transformers_vqa.sh
CLIP4Clip/train_msrvtt_tuning.sh
CLIP4Clip/train_msvd_tuning.sh
GPO/train_grid_wsl.sh
MDETR/finetune.sh

Please check and activate them respectively.
