### ISSUE TITLE
roberta-base

### ISSUE THREAD

**Issue by qiulesun** [Paranioar/UniPT#2]
@Paranioar 

Nice work ！

I aim to reproduce results on RefCOCO dataset. When following line is executed, the issue occurs, i.e., **ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on**.

[self.tokenizer = RobertaTokenizerFast.from_pretrained(text_encoder_type)
self.text_encoder = RobertaModel.from_pretrained(text_encoder_type)](https://github.com/Paranioar/UniPT/blob/main/MDETR/models/transformer.py#L59C9-L60C76)

However, my Internet connection is on constantly. So you can upload the roberta-base model you used and put them in corresponding folder, like pretrained_resnet101_checkpoint.pth put into pretrained_weights folder ?

**Comment by Paranioar** [comment]
> @Paranioar
> 
> Nice work ！
> I aim to reproduce results on RefCOCO dataset. When following line is executed, the issue occurs, i.e., **ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on**.
> However, my Internet connection is on constantly. So you can upload the roberta-base model you used and put them in corresponding folder, like pretrained_resnet101_checkpoint.pth put into pretrained_weights folder ?

There are many pre-trained model files that are automatically downloaded through related packages. Due to many affairs recently, I am sorry that I cannot organize and upload these cache documents right now.

I recommend you use [Clash.for.Windows-0.20.33-x64-linux.tar.gz](https://www.zrzz.site/posts/5760e5b0/) for network management, and then you can successfully download all the relevant models in the terminal.

**I plan to update the README.md in details *at the end of November***, which will include datasets links, environment configurations (docker or conda-pack), method descriptions, pre-trained model weights, our model weights, and etc.
